version: 2

updates:
  - package-ecosystem: bun
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "09:00"
      timezone: America/Los_Angeles
    groups:
      bun-minor-and-patch:
        patterns:
          - "*"
        update-types:
          - minor
          - patch

  - package-ecosystem: cargo
    directory: /native
    schedule:
      interval: weekly
      day: monday
      time: "09:00"
      timezone: America/Los_Angeles
    groups:
      cargo-minor-and-patch:
        patterns:
          - "*"
        update-types:
          - minor
          - patch

  - package-ecosystem: rust-toolchain
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "09:00"
      timezone: America/Los_Angeles

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "09:00"
      timezone: America/Los_Angeles
    groups:
      github-actions:
        patterns:
          - "*"
